name: single-cell perturbation benchmark
id: omni-perturb
description: Here, we benchmark different stages of an scPerturb-seq pipeline
benchmarker: "Atreya Choudhury"
version: "1.0"

software_backend: "conda"

software_environments:
  raw_data:
    name: Environment for raw MEX data fetching
    conda: envs/raw-data.yaml
  crispat:
    name: Environment for crispat guide assignment
    conda: envs/crispat.yaml
  kaichi:
    name: Environment for kaichi guide assignment
    conda: envs/kaichi.yaml
  metrics:
    name: Environment for guide assignment metrics
    conda: envs/metrics.yaml

stages:
  # - id: data
  #   resources:
  #     cores: 4
  #   outputs:
  #     - id: rawdata.h5ad
  #       path: "{dataset}.h5ad"
  #   modules:
  #     - id: omni-data
  #       name: omni-data hapiq fetcher
  #       software_environment: omni_data
  #       repository:
  #         url: https://github.com/btraven00/omni-data
  #         commit: main
  #       parameters:
  #         - source: "scperturb"
  #           accession:
  #             - "NormanWeissman2019"
  #             - "ReplogleWeissman2022_K562_essential"
  #             - "ReplogleWeissman2022_K562_gwps"
  #           include_ext: ".h5ad"

  - id: data
    outputs:
      - id: rawcounts.h5mu
        path: "{dataset}.h5mu"
    resources:
      cores: 6
      memory: "64GB"
    modules:
      - id: count-data
        name: Perturb-seq MEX fetcher and MuData converter
        software_environment: raw_data
        repository:
          url: https://github.com/omni-perturb/count-data
          commit: main
        parameters:
          - dataset_name: ["K562_essential", "rpe1"]

  - id: guide-assignment
    inputs:
      - rawcounts.h5mu
    outputs:
      - id: assignments.h5ad
        path: "{dataset}.h5ad"
    resources:
      cores: 1
    modules:
      - id: crispat
        name: crispat guide assignment models
        software_environment: crispat
        repository:
          # url: ../crispat
          url: https://github.com/omni-perturb/crispat
          commit: main
        parameters:
          - method: "pgmm"
            n_iter: 100
            # method: ["pgmm", "gauss", "2beta", "3beta"]
      - id: kaichi
        name: kaichi guide assignment models
        software_environment: kaichi
        repository:
          url: https://github.com/omni-perturb/kaichi
          commit: main
        parameters:
          - model: ["umi", "max", "ratio", "poisson_gauss"]

  - id: metrics
    inputs:
      - assignments.h5ad
      - rawcounts.h5mu
    outputs:
      - id: metrics.parquet
        path: "{dataset}.parquet"
      - id: metrics.tsv
        path: "{dataset}.tsv"
    resources:
      cores: 2
      memory: "16GB"
    modules:
      - id: metrics
        name: Guide assignment metrics
        software_environment: metrics
        repository:
          url: https://github.com/omni-perturb/metrics
          commit: ce181a0
